version: "3.9"
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    network_mode: container:gluetun
    restart: unless-stopped
    environment:
      - WEBUI_PORTS=9091
      - PUID=1026
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /volume1/Media/Downloads:/app/qBittorrent/downloads
