version: "3.9"
services:
  minidlna-desktop:
    image: giof71/minidlna
    container_name: minidlna
    network_mode: host
    environment:
      - MINIDLNA_ROOT_CONTAINER=V
      - MINIDLNA_DIR_V_1=/video
      - MINIDLNA_ENABLE_INOTIFY=YES
      - MINIDLNA_FRIENDLY_NAME=minidlna
      - PUID=1000
      - PGID=1000
    volumes:
      - /volume1/Media:/video
      - ./config/log:/log
      - ./config/db:/db
    restart: unless-stopped
