version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "root"
    networks:
      - traefik
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /volume1/Media:/media
    group_add:
      - "937" # id of videodriver from /etc/group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.i.nner.xyz`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
networks:
  traefik:
    name: traefik
    external: true
