version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "root"
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /volume1/Media:/media
    group_add:
      - "937" # id of videodriver from /etc/group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: "unless-stopped"
