version: "3"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
      - .private.env # provide WIREGUARD_PRIVATE_KEY
    ports:
      - 9091:9091
